sidekiq-book/config/routes.rb
#---
# Excerpted from "Ruby on Rails Background Jobs with Sidekiq",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/dcsidekiq for more book information.
#---
require "sidekiq/web"

Rails.application.routes.draw do
  resources :orders, only: [ :new, :create, :show ]
  resources :simulated_behaviors, only: [ :edit, :update ]
  root "welcome#show"

  mount Sidekiq::Web => "/sidekiq"
end

sidekiq-book/app/controllers/welcome_controller.rb
#---
# Excerpted from "Ruby on Rails Background Jobs with Sidekiq",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/dcsidekiq for more book information.
#---
require "net/http"

class WelcomeController < ApplicationController
  def show
    @service_statuses = ServiceStatus.all
  end
end

sidekiq-book/app/views/welcome/show.html.erb
<main class="text-center p-12">
  <h2 class="font-bold text-3xl mt-2">Welcome!</h2>
  <section class="mt-6">
    <p>
    <%= Order.count %> <%= "order".pluralize(Order.count) %> in the system.
    </p>
    <% Order.all.each do  |order| %>
      <%= link_to order_path(order), title: "Link to order #{order.id}" do %>
        <%= emoji([
          Emoji.new(char: "📦", description: "brown packing box"),
          Emoji.new(char: "🎁", description: "wrapped gift box"),
          Emoji.new(char: "🗳", description: "ballot box"),
        ].sample) %>
      <% end %>
    <% end %>
  <hr class="my-6">
  <h3 class="my-4 text-center font-bold text-2xl">Service Status</h3>
  <div class="grid grid-cols-2">
    <% @service_statuses.each do |service_status| %>
      <details <%= service_status.name == params[:open] ? "open": "" %> class="ml-4 mb-4" data-testid="service-<%= service_status.name.parameterize %>">
        <summary class="text-left font-bold text-xl mb-4">
          <%= service_status.name.humanize %>
          <%= service_status.status == true ? emoji("✅", "checkmark") : emoji("🛑", "stop sign") %>
          <% if service_status.name == params["updated_service"] %>
            <span class="text-sm font-normal italic">
              <%= emoji("👶","baby's head") %>
              Updated
            </span>
          <% end %>
        </summary>
        <section class="p-4 border rounded bg-white">
          <% if service_status.status == true %>
            <h4 class="font-semibold text-l text-left mb-2">Service Info</h4>
            <table class="table-fixed bg-gray-100 w-full">
              <% service_status.info.keys.sort.each do |key| %>
                <tr>
                  <td class="w-1/3 border px-4 py-2 text-left">
                    <%= key %>
                  </td>
                  <td class="w-1/2 border px-4 py-2 text-left">
                    <%= service_status.info[key] %>
                  </td>
                </tr>
              <% end %>
              <% if service_status.api? %>
                <tr>
                  <td class="w-1/3 border px-4 py-2 text-left">
                    Throttle?
                  </td>
                  <td class="w-1/2 border px-4 py-2 text-left" data-testid="throttle">
                    <%= service_status.throttle ? "Yes" : "No" %>
                  </td>
                </tr>
                <tr>
                  <td class="w-1/3 border px-4 py-2 text-left">
                    Crash?
                  </td>
                  <td class="w-1/2 border px-4 py-2 text-left" data-testid="crash">
                    <%= service_status.crash ? "Yes" : "No" %>
                  </td>
                </tr>
                <tr>
                  <td class="w-1/3 border px-4 py-2 text-left">
                    Time out after
                  </td>
                  <td class="w-1/2 border px-4 py-2 text-left" data-testid="sleep">
                    <%= service_status.sleep.to_i == 0 ? "No" : "#{service_status.sleep} seconds" %>
                  </td>
                </tr>
                <tr>
                  <td colspan="2" class="text-left">
                    <%= link_to "Manage…", edit_simulated_behavior_path(service_status.name), class: "text-blue-900 underline block px-4 py-2 font-semibold hover:text-blue-600", name: "manage" %>
                  </td>
                </tr>
              <% end %>
            </table>
          <% else %>
            <h4 class="font-semibold text-l text-left mb-2">Service Problem</h4>
            <p class="text-left">
              <%= service_status.status %>
            </p>
          <% end %>
        </section>
      </details>
    <% end %>
  </div>
  </section>
</main>