sidekiq-book/config/routes.rb
#---
# Excerpted from "Ruby on Rails Background Jobs with Sidekiq",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/dcsidekiq for more book information.
#---
require "sidekiq/web"

Rails.application.routes.draw do
  resources :orders, only: [ :new, :create, :show ]
  resources :simulated_behaviors, only: [ :edit, :update ]
  root "welcome#show"

  mount Sidekiq::Web => "/sidekiq"
end

sidekiq-book/app/controllers/simulated_behaviors_controller.rb
#---
# Excerpted from "Ruby on Rails Background Jobs with Sidekiq",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/dcsidekiq for more book information.
#---
class SimulatedBehaviorsController < ApplicationController
  def edit
    @service_status = ServiceStatus.find(params[:id])
  end

  def update
    service_status = ServiceStatus.find(params[:id])
    service_status.update(service_status_params)
    redirect_to root_path(updated_service: service_status.name, open: service_status.name)
  end

private

  def service_status_params
    params.require(:service_status).permit(:sleep).merge({
      throttle: params[:service_status][:throttle].to_i != 0,
      crash:    params[:service_status][:crash].to_i != 0,
    })
  end
end

sidekiq-book/app/views/simulated_behaviors/edit.html.erb
<main class="p-4 w-full md:w-1/2">
  <div class="flex">
    <%= emoji("🎛", "four adjustable knobs", css_class: "text-4xl") %>
    <%= emoji(@service_status.emoji, css_class: "text-4xl ml-2") %>
    <header class="ml-4">
      <h1 class="text-4xl text-left flex">
        Simulate <%= @service_status.name.humanize %> Behavior
      </h1>
      <h2 class="text-xl text-left font-extralight italic flex">
        Make it behave badly
      </h2>
    </header>
  </div>
  <section class="mt-4 bg-gray-200 rounded p-4">
    <%= form_with model: @service_status, url: simulated_behavior_path(@service_status.name), method: :put do |f| %>
      <div class="flex flex-col mt-2 mb-4">
        <%= f.label :throttle, class: "flex items-baseline mt-1" do %>
          <%= f.check_box :throttle, class: "w-5" %>
          <span>
            Throttle?
          </span>
        <% end %>
        <div class="flex mb-1">
          <span class="w-5">&nbsp;</span>
          <span class="italic text-sm text-gray-600">Service will return a 429 to each request</span>
        </div>
        <%= f.label :crash, class: "flex items-baseline mt-1" do %>
          <%= f.check_box :crash, class: "w-5" %>
          <span>
            Crash?
          </span>
        <% end %>
        <div class="flex mb-1">
          <span class="w-5">&nbsp;</span>
          <span class="italic text-sm text-gray-600">Service will return a 5xx to each request</span>
        </div>
        <%= f.number_field :sleep, class: "p-2 w-1/4 border border-1 rounded  mt-1" %>
        <%= f.label :sleep, class: "ml-1 mt-1" do %>
          <span>
            Time out after (seconds)
          </span>
          <span class="block italic text-sm text-gray-600">Cause the service to sleep this many seconds before returning a response</span>
        <% end %>
      </div>
      <%= f.button class: "button" do %>
        Update <%= @service_status.name.humanize %>
      <% end %>
    <% end %>
  </section>
</main>