sidekiq-book/config/routes.rb
#---
# Excerpted from "Ruby on Rails Background Jobs with Sidekiq",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/dcsidekiq for more book information.
#---
require "sidekiq/web"

Rails.application.routes.draw do
  resources :orders, only: [ :new, :create, :show ]
  resources :simulated_behaviors, only: [ :edit, :update ]
  root "welcome#show"

  mount Sidekiq::Web => "/sidekiq"
end

sidekiq-book/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SidekiqBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= yield :page_specific_head_section %>
  </head>

  <body class="bg-gray-100" 
        data-controller="<%= controller_name %>"
        data-action="<%= action_name %>">
    <header>
      <nav class="bg-black text-white px-4 py-4 flex items-center">
        <h1 class="text-xl uppercase tracking-tight font-medium">
          <a href="/">
            <%= emoji(Emoji.new(char: "👾", description: "8-bit space invader")) %>
            Sidekiq Book App
          </a>
        </h1>
        <% if controller_name == "orders" && action_name.in?(["new","create"]) %>
        <% else %>
          <%= link_to new_order_path, class: "text-sm hover:text-gray-200 font-light hover:underline ml-7 " do %>
            Add An Order <span role="img" description="right arrow">&rarr;</span>
          <% end %>
        <% end %>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>